echo "  _   _                  _                 _  "
echo " | | | |_   _ _ __  _ __| | __ _ _ __   __| | "
echo " | |_| | | | | ,_ \| ,__| |/ _\ | ,_ \ / _, | "
echo " |  _  | |_| | |_) | |  | | (_| | | | | (_| | "
echo " |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_| "
echo "        |___/|_|                              "
echo "                             " 
echo "by Stephan Raabe (2023)"
echo "------------------------------------------------------"
echo "Dotfiles Version 2.5"
echo ""
echo "This script will install or update Hyprland and the corresponding dotfiles."
echo "PLEASE BACKUP YOUR CONFIGURATION IF NEEDED."
echo ""