echo "  ___ _____ ___ _     _____  "
echo " / _ \_   _|_ _| |   | ____| "     
echo "| | | || |  | || |   |  _|   "
echo "| |_| || |  | || |___| |___  "
echo " \__\_\|_| |___|_____|_____| "
echo "                             " 
echo "by Stephan Raabe (2023)"
echo "------------------------------------------------------"
echo "Dotfiles Version 2.5"
echo ""
echo "This script will install or update Qtile and the corresponding dotfiles."
echo "PLEASE BACKUP YOUR CONFIGURATION IF NEEDED."
echo ""